[book]
title = "The Ghost of SVR4"
authors = ["Lee Hanken"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = ""
git-repository-icon = "fa-git"
additional-css = ["theme/custom.css"]
additional-js = []

# Enable EPUB output
[output.epub]
# Optional settings for EPUB:
cover-image = "src/cover.png"
# additional-css = ["custom.css"]

# Enable PDF output
[output.pdf]
# Optional settings for PDF:
landscape = false
display-header-footer = true
header-template = "<div style=\"font-size: 10px; width: 100%; text-align: right; padding-right: 1cm;\">The Ghost of SVR4</div>"
footer-template = "<div style=\"font-size: 10px; width: 100%; text-align: center;\"><span class=\"pageNumber\"></span> / <span class=\"totalPages\"></span></div>"
margin-top = 1.0
margin-bottom = 1.0
margin-left = 0.75
margin-right = 0.75
